import React from 'react'
import { Link } from 'react-router-dom'
import Layout from '../components/shared/Layout'
import ImageIcons from '../components/imageComponent/ImageIcons';

const TermsConditions = () => {
    return (
        <Layout>
            {/* Hero Section */}
            <section className='relative'>
                <div className='relative w-full overflow-hidden py-[5%] after:content after:absolute after:left-0 after:right-0 after:top-0 after:w-full after:h-full after:bg-[#00A51A] after:opacity-50'>
                    <img src={ImageIcons.contactheaderbg} alt='Commissions' className='absolute top-[50%] left-[50%] translate-y-[-50%] translate-x-[-50%] w-full h-full object-center object-cover' />
                    <div className='relative w-full h-full flex flex-col justify-center items-center z-10 px-[15px] py-[15px]'>
                        <h1 className="capitalize text-white text-center">Terms & Conditions</h1>
                        <div className="text-center mt-[10px]">
                            <p className='mb-0'>
                                <Link className="text-white font-medium hover:underline" to="/">Home</Link>
                                <span className="px-[10px] text-white font-medium inline-block">/</span>
                                <span className="inline-block text-white font-medium ">Terms & Conditions</span>
                            </p>
                        </div>
                    </div>
                </div>
            </section>

            <section className='md:py-[70px] max-md:py-[50px]'>
                <div className="lg:container mx-auto px-4">
                    <p>PLEASE READ THE FOLLOWING TERMS OF SERVICE CAREFULLY BEFORE USING THE SITE OR SIGNING UP FOR ANY SERVICE THAT VELOSTING OFFERS.</p>
                    <h3>INTRODUCTION</h3>
                    <p className='mb-[10px]'>Velosting, its affiliates and their successors and assigns (collectively referred to as "Velosting") makes available the web hosting and related services described in Velosting's published service descriptions subject to these Terms of Service (the "TOS").</p>
                    <p className='mb-[30px]'>For the purposes of the TOS, the word "you" means the individual requesting one or more services provided by Velosting, and, if applicable, includes any other legal entity on behalf of which an individual makes such a request.  Additionally, you agree not to make such a request on behalf of any other legal entity unless you have the authority to bind that legal entity to the TOS.</p>
                    <h3 className='text-[20px] mb-[10px]'>ACCEPTANCE OF TERMS</h3>
                    <p className='mb-[15px]'><b>Capacity:</b> You represent and warrant to Velosting that you have the capacity to enter into a legal agreement in the province, state, territory or country in which you reside. If you do not have the capacity to enter into a legal agreement in the province, state, territory or country in which you reside, do not request services from Velosting unless your parent or guardian enters into the TOS on your behalf.</p>
                    <p className='mb-[15px]'>PLEASE READ THE TOS CAREFULLY. BY CLICKING ON THE "I AGREE" BUTTON OR CHECK BOX ON THE ORDER FORM FOR ANY SERVICE PROVIDED BY VELOSTING, YOU ARE AGREEING TO BE BOUND BY THE TOS AND ALL TERMS AND CONDITIONS INCORPORATED BY REFERENCE IN THE TOS. YOUR USE OF THE SERVICES FURTHER CONFIRMS YOUR ACCEPTANCE OF THESE TOS.</p>
                    <p className='mb-[30px]'>You represent and warrant to Velosting that your use of any service that it provides will not violate any applicable law or regulation in the province, state, territory or country in which you reside. If you are unable or unwilling to do so, do not request services from Velosting.</p>
                    <h3 className='text-[20px] mb-[10px]'>YOU</h3>
                    <p className='mb-[15px]'><b>Services:</b> The services that you request from Velosting by means of the online order form on the Site or otherwise in writing and which Velosting agrees to provide subject to these TOS are the "Services".</p>
                    <p className='mb-[15px]'><b>Your Information:</b> You represent and warrant that any information you provide about yourself is true, and you will maintain and promptly update such information to keep it true and current.</p>   
                    <p className='mb-[15px]'><b>Privacy:</b> You have read Velosting's Privacy Policy and consent to the use of your personal information as described therein. </p>
                    <p className='mb-[15px]'><b>Communications:</b> Velosting reserves the right to communicate with you regarding the Services and your use of the Site. You consent to Velosting's use of any contact information that you provide to Velosting in doing so.</p>
                    <p className='mb-[15px]'><b>Passwords:</b> If you are given a username and/or a password for the purpose of accessing certain features of the Services or certain features of the Site, you are responsible for all activities conducted under that username or password, and you will take all necessary steps to ensure that no one other than you uses that username or password and that password is kept confidential. If you have any reason to believe that any password assigned to you has become known to or been used by any other person, you will inform Velosting immediately</p>
                    <p className='mb-[15px]'><b>Changing Passwords:</b> Velosting may, at any time, change any username or password assigned by Velosting to you, and Velosting will notify you when it does so.</p>
                    <p className='mb-[30px]'><b>Insurance:</b> Client shall maintain, at its sole cost, insurance against such risks and in such amounts that could reasonably be expected by persons acting prudently and engaged in similar activities as Client.</p>
                    <h3>DESCRIPTION OF SERVICES</h3>
                    <h4 className='text-[20px] mb-[10px]'>General</h4>
                    <p className='mb-[10px]'><b>Description:</b> For each package of web hosting and related services that Velosting makes available to its customers, Velosting has prepared and published a specification (each a "Service Description"). The Service Descriptions are available on <Link to="https://www.Velosting.in">https://www.Velosting.in</Link> (the "Site").</p>
                    <p className='mb-[30px'><b>Changes to Services:</b> Velosting may modify its services and the corresponding Service Descriptions from time to time. Please refer to the Site for the most current Service Descriptions. Velosting may also send an email notice of the change to its affected customers.</p>
                    <h4 className='text-[20px] mb-[10px]'>Hosting Services</h4>
                    <p className='mb-[10px]'>Any Service identified as "Hosting" in its Service Description is a Hosting Service.</p>
                    <p className='mb-[20px]'><b>Hosting Environment:</b> Velosting shall: (i) maintain and operate the hardware used to host your website(s) (including monitoring the servers used on 24/7 basis); and (ii) use commercially reasonable efforts to maintain reasonable temperature and humidity levels, fire suppression controls, power conditioning equipment and uninterruptible power supplies for the proper ongoing operation of Velosting's hosting hardware.</p>
                    <h4 className='text-[20px] mb-[10px]'>SSD Storage</h4>
                    <p className='mb-[15px]'>Velosting shall provide SSD storage for your website(s).</p>
                    <p className='mb-[15px]'><b>Internet:</b> Velosting shall provide an Internet connection linking your hosted website(s) to the Internet.</p>
                    <p className='mb-[15px]'><b>Remote Access:</b> You will be given remote access to upload files for your hosted website(s) provided that you do so in a manner consistent with the TOS.</p>
                    <p className='mb-[15px]'><b>Routing:</b> When Velosting hosts a website on your behalf, Velosting will route one or more domain names to that website. The exact number of domain names that Velosting will route on your behalf will depend on the Hosting Service to which you subscribe. Check the applicable Service Description for more information.</p>
                    <p className='mb-[15px]'><b>Backup:</b> You acknowledge that unless you subscribe to a Hosting Service that expressly includes the independent backup of Your Content (as defined below) as a service, Velosting's backup activities are primarily for Velosting's own disaster recovery purposes, and that <b>YOU ARE RESPONSIBLE FOR THE STORAGE, BACKUP AND ARCHIVING OF YOUR CONTENT.</b> Also note, Hosting Services include access to one or more tools via your Control Panel that allow you to backup Your Content. Please use these tools and backup Your Content frequently. Velosting Automated Website Backup is an optional service available for an additional fee or which may be included for no charge in some Hosting Services that will automatically backup Your Content on an ongoing basis for your convenience. Please note that this service is provided as-is and without warranty in respect to performance. If you are using this service it is still your responsibility to review your backups from time to time to ensure all of your data is backed up correctly and to notify us of any concerns you have.</p>
                    <p className='mb-[15px]'><b>Availability:</b> A Hosting Service is "Available" if the: (a) the hardware being used to provide it is operating; and (b) the Internet connection provided as part of the Hosting Service is operational.</p>
                    <p className='mb-[15px]'><b>Measure:</b> Velosting will use reasonable efforts to ensure that the Hosting Services will be Available other than for "Scheduled Maintenance" at least 99.9% of the time, measured monthly. Any maintenance or other work performed on Velosting's technology infrastructure that takes place during the Maintenance Window or with at least 48 hours' prior notice posted to the Site is "Scheduled Maintenance".</p>
                    <p className='mb-[15px]'><b>Cooperation:</b> You acknowledge that it is important to coordinate your maintenance activities with those of Velosting, and you will not conduct any maintenance activities on Your Content during any Maintenance Window without first obtaining written confirmation that Velosting will not be performing any maintenance activities during that Maintenance Window.</p>
                    <p className='mb-[30px]'><b>Free Domain Name:</b> If the cost of registering or renewing a single domain name for one year is included in the annual Fees that you are being charged for a Hosting Service (see the applicable Service Description to find out if it is included and the eligible types of domain names) and the domain name that you wish to register or renew for use with the website being hosted is both an eligible type of domain name and available, Velosting will register or renew (as applicable) the domain name for you. If Velosting does so and you continue to subscribe to such Hosting Services for a period of at least 12 months, Velosting will not charge you its then-current fee for registering or renewing a domain name (as applicable). <b>HOWEVER, IF THE HOSTING SERVICES ARE TERMINATED LESS THAN 12 MONTHS AFTER REGISTERING OR RENEWING THE DOMAIN NAME (THIS INCLUDES DURING THE FIRST 30 DAYS) OR YOU ATTEMPT TO TRANSFER THE DOMAIN NAME DURING THAT 12 MONTH PERIOD, VELOSTING WILL CHARGE YOU AND YOU ARE REQUIRED TO PAY VELOSTING'S THEN CURRENT FEE FOR REGISTERING OR RENEWING A DOMAIN NAME (AS APPLICABLE).</b></p>
                    <h3>Domain Names Registration Services</h3>
                    <p className='mb-[15px]'><b>Assistance with Registering Only:</b> Velosting may assist you to register one or more top-level or second-level domain names (the "Domain Name Registration Service"). For each such domain name registered Velosting's involvement ends with the registration. You will be the registrant, administrative contact and technical contact, and you agree to be bound by all applicable terms and conditions published by the applicable registrar.</p>
                    <p className='mb-[15px]'><b>Maintenance of Domain Names:</b> You are responsible for the ongoing maintenance, control and use of any domain name registered in your name and for any fees or taxes associated with its maintenance. To maintain your domain name registration you will need to interact directly with the applicable registrar. <b>FOR GREATER CLARITY, YOU ARE RESPONSIBLE FOR: (i) RENEWING THE REGISTRATION AND ENSURING THAT IT DOES NOT LAPSE; AND (ii) ADDRESSING ANY ISSUES RELATING TO YOUR DOMAIN NAME. VELOSTING IS NOT RESPONSIBLE FOR DOING SO.</b></p>
                    <p className='mb-[15px]'><b>Please note that:</b> (i) Velosting is not able to guarantee that a proposed domain name is available for registration or that a registrar will register it; (ii) Velosting will not assist with the registration on your behalf of a proposed domain name in any top-level or second-level domain unless expressly directed by you to do so; and (iii) Velosting may but is not obligated to inform you of any proposed or new top-level or second-level domains.</p>
                    <p className='mb-[15px]'><b>Privacy Registration Service:</b> Some registrars allow domain names to be registered without publishing the registrant's name and contact information others do not. If you wish to take advantage of any such privacy service for a domain name and you are using the Domain Name Registration Service to register the domain name, you are responsible for informing Velosting in writing prior to the registration of the domain name that you wish to take advantage of the registrar's privacy service. You acknowledge that the privacy service is provided by the applicable registrar, not Velosting.</p>
                    <p className='mb-[15px]'><b>As is:</b> Assistance with registering domain names and securing related privacy services is provided "as is" and without any warranties, representations or conditions whatsoever.</p>
                    <p className='mb-[15px]'><b>Domain Redemption Fee:</b> If your domain was registered with Velosting and has expired, but you wish to recover the domain, Velosting may be able to recover the domain if it is still within the redemption period. To recover a domain name that has expired but which is still within the redemption period, Velosting must pay a redemption fee, which in turn will be passed on to you the customer. Please note that this domain redemption fee does not include the registration price of the domain that will still need to be paid to register the domain for the next year. If the domain name is not renewed or acquired during the redemption period, it will be made available again to the general public after the redemption period completes. Only domains that have been registered with Velosting can be re-registered after expiration of the domain. If the domain that has expired was registered at another company, you will need to contact that registrar to recover the domain from the redemption period.</p>
                    <p className='mb-[15px]'><b>Resale:</b> If you have received written permission from Velosting to resell all or part of the Services that you are receiving pursuant to this Agreement, you are responsible for providing support to your clients. If Velosting is contacted directly by any such client, Velosting may suspend all or part of the Services that it is providing to you. If Velosting does so, Velosting will give you notice of the suspension and the reason for the suspension. Once you have satisfied Velosting that you have taken reasonable steps to inform your clients that they are to contact you for support and to ensure that you are providing that support, Velosting will lift the suspension. There is no abatement of Fees during any such suspension. Furthermore, any acts and omissions of your clients that would be breaches of this Agreement had they been your acts or omissions are your responsibility and will be treated as if they are your acts and omissions.</p>
                    <p className='mb-[30px]'><b>Additional Services:</b> Any additional services related to the Hosting Services or Domain Name Registration Services that are requested by you and that Velosting in its sole discretion provides ("Additional Services") are deemed to be Services provided pursuant to these TOS, and they will be provided at Velosting's then-current rates.</p>
                    <h3>Support</h3>
                    <p className='mb-[15px]'><b>FAQ:</b> Velosting maintains a list of frequently asked questions and technical support articles relating to the Hosting Services on the Site.</p>
                    <p className='mb-[15px]'><b>Technical Support:</b> Velosting will provide technical support relating to the Hosting Services via its help desk. The help desk aims to provide technical support 24/7/365. The help desk can be reached by: (i) telephone; (ii) email; and/or (iii) chat. The email address and the telephone number that you should use are set out on the Site.</p>
                    <p className='mb-[15px]'><b>Verifiable:</b> Velosting will use commercially reasonable efforts to resolve each problem reported to Velosting's help desk and verifiable as being a problem or deficiency with the Hosting Services.</p>
                    <p className='mb-[30px]'><b>Assistance:</b> When you report a problem to Velosting's help desk, you will provide: (i) any assistance reasonably necessary to allow Velosting to verify and resolve that problem; and (ii) all information that you are reasonably able to provide with respect to any problem.</p>
                    <h3>CONTENT</h3>
                    <p className='mb-[15px]'><b>Intellectual Property:</b> No intellectual property rights are transferred by Velosting to you by these TOS.</p>
                    <p className='mb-[15px]'><b>Your Content:</b> "Your Content" means all materials, information, data or code that you upload, store, transmit, receive or process in connection with the Services. You hereby grant to Velosting and its directors, officers, employees, agents, consultants or subcontractors the right to use, reproduce, transmit and delete (as applicable) Your Content in such manner as may be necessary to enable Velosting to perform the Services and otherwise exercise any right or perform any obligations under this Agreement.</p>
                    <p className='mb-[30px]'><b>Monitoring Your Content:</b> Although Velosting is not obligated to monitor content and assumes no responsibility for Your Content or the content of its other customers, Velosting reserves the right, subject to all applicable laws, to investigate Your Content and may block access to, refuse to host, or remove any information or material that it deems to be in breach of its policy.</p>
                    <h3>ACCEPTABLE USE</h3>
                    <p className='mb-[10px]'><b>Unacceptable Use:</b> Unacceptable use refers to any unlawful, illegal or inappropriate use as set out in this section 6. You may not use the Services or Velosting's technology infrastructure in any manner that constitutes an unacceptable use. Unlawful or illegal use is the creation, collection, transmission, storage or exchange of any material in violation of any applicable law or regulation. Inappropriate use includes any use or behaviour that may: (i) jeopardize Velosting's products, services, technology infrastructure or ability to operate; or (ii) expose Velosting to civil liability. Unlawful, illegal or inappropriate use includes use of the Services to:</p>
                    <ul className='list-disc pl-[20px] mb-[30px]'>
                        <li>Possess, store, view, download, transmit, distribute (by any peer-to-peer service or otherwise) or traffic any materials that</li>
                        <li>Include child pornography;</li>
                        <li>Promote, sell or otherwise disseminate adult related material, pornography or other erotic material that contains nudity or other content determined at our sole discretion as adult-related regardless of merit, including but not limited to adult thumbnail galleries and banner exchanges;</li>
                        <li>Infringe any person's copyright or other intellectual property right (including unlicensed or improperly licensed applications, music, games or other materials);</li>
                        <li>Wilfully promote hatred against or defame any identifiable individual, group or other organization; including but not limited to promoting hate, violence, or intolerance based on race, age, gender identity, ethnicity, religion, or sexual orientation.</li>
                        <li>Promote or advocate human trafficking in any way as determined at our sole discretion;</li>
                        <li>Promote prostitution or escort services;</li>
                        <li>Promote gambling, casinos, gaming, sports betting, daily fantasy sports, lottery or chain letters regardless of content or origin and regardless of your citizenship or the legality of such activities within your country or jurisdiction;</li>
                        <li>Promote or sell illegal drugs or drug paraphernalia;</li>
                        <li>Advertise, advocate or operate get rich quick schemes or any high-yield interest programs (HYIP), ponzi or pyramid schemes, prime banks programs, bank debentures/bank debenture trading programs or related sites;</li>
                        <li>Can be used for attacking computer systems, networks or internet users and defacing websites, including but not limited to IP scanners, bruteforce programs, spam scripts, executables, mail bombers or other tools or applications;</li>
                        <li>Include any form of malware;</li>
                        <li>Impersonate or falsely state or otherwise misrepresent your identity or affiliation with any person or entity;</li>
                        <li>Wilfully bypass or subvert the physical, logical or procedural safeguards such as firewalls, web-filtering software or other access controls used by anyone to gain unauthorized access to anyone's technology infrastructure or distributing computer programs designed to assist in doing so;</li>
                        <li>Operate file dumps / mirror scripts (similar to rapidshare), anonymous or bulk SMS Gateways or fraudulent sites including but not limited to sites listed at aa419.org and escrow-fraud.com;</li>
                        <li>Broadcast or stream live sporting events including but not limited to UFC, NASCAR, FIFA, NFL, NHL, MLB, WWE or television;</li>
                        <li>Operate cryptocurrency / bitcoin miners; or</li>
                        <li>Undertake any act in violation of any applicable local, provincial, state, national or international law or regulation including any laws relating to the export of data or software, or the protection of human rights; and</li>
                        <li>Unacceptable uses of the Services or Velosting's technology infrastructure may also include but are not limited to hosting materials or performing activities such as: unsolicited mailings, newsgroup spamming, hosting topsites for the purpose of distributing, storing or archiving warez releases, copyrighted MP3, illegal content, copyright infringement, trademark infringement, cracks, software serial numbers, and running of any scripts, executables, or other programs or processes that can in any way adversely affect the performance of Velosting's technology infrastructure. Velosting will be the sole and final arbiter as to what constitutes a violation of this policy.</li>
                    </ul>
                    <p className='mb-[15px]'><b>Disruptive Uses:</b> You may not use the Services or Velosting's technology infrastructure in any manner that interferes with or disrupts Velosting's other customers. When any of the following events occurs in relation to any hosted web site, it is a disruptive use, a breach of these TOS and Velosting may exercise its rights including suspending Services:</p>
                    <ul className='list-disc pl-[20px] mb-[30px]'>
                        <li>Generating a daily, weekly or monthly volume of network traffic that is excessive in relation to amount of network traffic typically generated by Velosting's other clients who have purchased similar hosting services;</li>
                        <li>Generating spikes in network traffic usage that are out of proportion (in volume or frequency) to those typically generated by Velosting's other clients who have purchased similar hosting services;</li>
                        <li>On a daily, weekly or monthly basis, consuming CPU or other processing resources in a manner that is excessive in relation to amount of network traffic typically generated by Velosting's other clients who have purchased similar hosting services;</li>
                        <li>Even if they do not come within (a), (b) or (c) above, running peer-to-peer applications, peer-to-peer file sharing, proxy servers, bit torrent, online gaming servers, proxy server network, interactive relay chat (IRC), interactive chat applications, membership or community sites, file sharing, video sharing, photo sharing or other resource intensive services or applications.</li>
                        <li>Using SSD storage to store materials unrelated to or unnecessary for the operation of the web site for which the Hosting Services were purchased (for example, using SSD storage for data warehousing, email storage, backups of emails accounts, backups of all or part of any computing, telecommunications or mobile device or other forms of mass data storage); or</li>
                        <li>Or the sending of any commercial electronic messages promoting the web site or otherwise directing attention to the web site to any recipient without the recipient's consent</li>
                        <li>No "Spam": UCE/UBE or "spam" originating from a server located on our network or associated with a Velosting server is not tolerated. This includes any email that promotes websites hosted on a server located on the Velosting network, but which is sent from an email address not associated with a Velosting account.</li>
                    </ul>
                    <p className='mb-[15px]'><b>Music, Image and Video Files:</b> Responding to and addressing copyright complaints is a time consuming process. From time to time, Velosting scans its servers looking for MP3, MP4 and other file formats commonly used for music, images or video. If such files are detected amongst Your Content, Velosting may ask you to demonstrate that they are: (i) owned or properly licensed by you; and (ii) if licensed, not being used in a manner that is inconsistent with that license. If you fail to do so for any file or, in the alternative, remove the file from Velosting's servers, it is a breach of this section and Velosting may exercise its rights under these TOS.</p>
                    <p className='mb-[15px]'><b>Reporting:</b> If you become aware that any person has committed, is likely to have committed or is likely to commit any act described, you will promptly report it to the help desk from which you receive technical support.</p>
                    <p className='mb-[15px]'><b>Investigation:</b> Velosting reserves the right to investigate suspected breaches of this section, and you agree to cooperate with Velosting when asked to assist in any such investigation.</p>
                    <p className='mb-[15px]'><b>Breaches:</b> If you breach this section , it is probable (in Velosting's sole discretion) that you have breached or it is likely that you will breach this section (also in Velosting's sole discretion), Velosting in its sole discretion may suspend or revoke your access to the Services or Velosting's technology infrastructure. Breaches of this section may also result in you incurring criminal prosecution or civil liability.</p>
                    <p className='mb-[30px]'><b>Others Breaches:</b> Velosting assumes no liability for enforcing or not enforcing the provisions in its other service agreements relating to acceptable use.</p>
                    <h3 className='text-[20px] mb-[10px]'>IP ADDRESSES</h3>
                    <p className='mb-[30px]'>Velosting may assign one or more Internet Protocol addresses to you for use with the Services. You acknowledge that you have no right, title or interest in or to any IP addresses assigned to you by Velosting or its representatives in connection with any Services. Velosting or its suppliers may change any such address at any time, but Velosting will use reasonable efforts to give you notice of any change if the affected IP address is a fixed IP address.</p>
                    <h3>PAYMENT</h3>
                    <p className='mb-[15px]'><b>Fees:</b> The fixed fees and/or rates applicable to any Service are set out in the online order form for the Service (the "Fees"). They may include one-time fees (these are typically for setting up the service) and recurring fees. PLEASE NOTE THAT THE ONLINE ORDER FORM MAY ALSO SET OUT A RATE INCREASE THAT WILL BECOME EFFECTIVE UPON THE EXPIRATION OF A PROMOTIONAL RATE. SUCH AN INCREASE WILL HAPPEN WITHOUT FURTHER NOTICE TO YOU. Otherwise, Velosting will give you at least 30 days prior written notice of any increase to the Fees.</p>
                    <p className='mb-[15px]'><b>Promotions:</b> From time to time, Velosting may offer its services to new or existing clients at discounted or promotional rates. You acknowledge that any such promotion is only applicable to one of your Services if the promotion or discount is clearly set out as applicable on the online order form used that you used to order the Service.</p>
                    <p className='mb-[15px]'><b>Expenses:</b> Unless expressly set out otherwise in an applicable Service Description, you will reimburse Velosting for all registrar's fees or other related expenses incurred by Velosting in relation to any third-party service.</p>
                    <p className='mb-[15px]'><b>Taxes:</b> You will pay any present or future sales, goods and services, excise, value-added, or other similar taxes including any related interest or penalties (imposed at any time by any governmental authority) arising from or related to any Services other than taxes based on Velosting's net income.</p>
                    <p className='mb-[15px]'><b>Payment of Fees:</b> Velosting accepts payment by credit card (Visa, MasterCard or American Express), Alipay, and PayPal. Available payment types may vary from region to region. Information on the payment types accepted in your jurisdiction is available on the Site.</p>
                    <p className='mb-[15px]'><b>In Advance:</b> Payment for Hosting Services is in advance. When you order a Hosting Service, you are required to pay the full amount of Fees for the initial term and applicable taxes. When a Hosting Service renews, you are required to pay the full amount of Fees for the renewal term and applicable taxes. A Hosting Service renews when it has not been terminated by you prior to the last date of the initial term or any renewal term for which you have paid.</p>
                    <p className='mb-[15px]'><b>Additional Services:</b> Fees for Additional Services, applicable taxes and reimbursable expenses are due at the end of the month in which they are incurred.</p>
                    <p className='mb-[15px]'><b>Automatic Charging:</b> When Velosting is entitled in accordance with this Agreement to any Fees, applicable taxes or expenses, such amounts will be automatically charged to the credit card, Alipay, or PayPal account that Velosting has on file for you and you authorize Velosting to do this. Velosting will send an invoice for these amounts to the email address that it has on file for you before doing so.</p>
                    <p className='mb-[30px]'><b>30 Day Guarantee of Hosting Services:</b> If at any time during the 30 day period beginning on the date that you purchase Hosting Services for the first of your websites to be hosted by Velosting you are not satisfied with the Hosting Services that you are receiving, you may terminate this Agreement by using the web-based tool that Velosting provides to you to manage your account to terminate the Hosting Service. If you do so, you will receive a refund. PLEASE SEE OUR CANCELLATION AND REFUND POLICY FOR REFUND RULES PERTAINING TO HOSTING SERVICES AND OTHER SERVICES.</p>
                    <h3>TERM</h3>
                    <p className='mb-[30px]'><b>Term:</b> This Agreement shall be effective as of the date on which you order your first Service and shall continue until terminated in accordance with the terms and conditions set out in this Policy.</p>

                    <h3>SUSPENSION AND TERMINATION</h3>
                    <p className='mb-[20px]'><b>Suspension:</b> If you breach any of these TOS, Velosting may, in its sole discretion, restrict or suspend the Services, without prior notice to you and without an opportunity to cure the breach. If you are given an opportunity to and you cure the breach or you demonstrate to Velosting satisfaction that you have taken steps to prevent future breaches of the TOS, Velosting will lift the restriction or suspension. Velosting will give you notice of any suspension or restriction. Whether or not a restriction affects your access to Your Content is in Velosting's sole discretion. PLEASE NOTE THAT FEES WILL BE CHARGED DURING THE PERIOD OF ANY SUSPENSION OR RESTRICTION OF SERVICES.</p>
                    <p className='mb-[20px]'><b>By You:</b> You may terminate any Service at any time by using the web-based tool that Velosting provides to you to manage your account to terminate the Service. PLEASE NOTE: any amounts paid in advance for Services will not be refunded.</p>
                    <p className='mb-[10px]'><b>By Velosting:</b> Velosting may terminate any Service by giving you at least 30 days written notice of the termination date. Velosting may terminate this Agreement immediately and without prior notice to you:</p>
                    <ul className='list-disc pl-[20px] mb-[20px]'>
                        <li>if you breach section “Acceptable Use” of this policy;</li>
                        <li>if you breach section “Payment” of this policy and do not cure that breach within 10 days of the breach; or</li>
                        <li>if you breach any other section of these TOS and do not cure that breach within 15 days.</li>
                    </ul>
                    <p className='mb-[30px]'><b>Renewals:</b> Services purchased for a set period (for example, three years) will be automatically renewed upon the expiry of that period unless you give Velosting written notice of your intention to terminate them at least 30 days prior to the expiry of that period. They will be renewed at Velosting's then current rates for such Services.</p>
                    <h3>WARRANTIES AND DISCLAIMERS</h3>
                    <p className='mb-[30px]'>THE INTERNET IS A COMPLEX NETWORK OF EQUIPMENT, SERVICES, AND PROVIDERS OF INFORMATION, THUS THE SERVICE MAY NOT BE AVAILABLE TO YOU AT ALL TIMES. YOU ACKNOWLEDGE THAT THE HOSTING SERVICES AND OTHER SERVICES MAY NOT ALWAYS BE AVAILABLE, AND WITH THE EXCEPTION OF ANY EXPRESS WARRANTIES CONTAINED IN THIS AGREEMENT, VELOSTING EXPRESSLY DISCLAIMS ANY OTHER REPRESENTATIONS, WARRANTIES, OR CONDITIONS WITH RESPECT TO THE HOSTING SERVICES OR OTHERWISE ARISING FROM THIS AGREEMENT WHETHER EXPRESS OR IMPLIED, PAST OR PRESENT, STATUTORY OR OTHERWISE, INCLUDING WITHOUT LIMITATION, ANY IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY THAT THE HOSTING SERVICES WILL BE UNINTERRUPTED OR ERROR FREE.</p>
                    <h3>LIMITATIONS OF LIABILITY</h3>
                    <p className='mb-[15px]'><b>Limit:</b> IN NO EVENT SHALL THE TOTAL CUMULATIVE LIABILITY OF VELOSTING (INCLUDING ITS REPRESENTATIVES AND SUPPLIERS) TO YOU, THE CLIENT, FOR ANY CLAIMS ARISING OUT OF OR RELATING TO THIS AGREEMENT, EXCEED THE AMOUNT PAID BY YOU, THE CLIENT, DURING THE 03 MONTH PERIOD PRECEDING THE DATE ON WHICH YOU, THE CLIENT, MAKE YOUR FIRST CLAIM FOR DAMAGES.</p>
                    <p className='mb-[15px]'><b>Indirect Damages:</b> Velosting (INCLUDING ITS REPRESENTATIVES AND SUPPLIERS) SHALL NOT BE LIABLE TO YOU, THE CLIENT, OR YOUR END USERS IN ANY WAY WHATSOEVER, FOR ANY INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES, INCLUDING BUT NOT LIMITED TO, LOSS OF DATA, REVENUE OR PROFIT RESULTING FROM OR ARISING IN CONNECTION WITH THIS AGREEMENT OR THE PROVISION OR USE OF THE HOSTING SERVICES. THIS LIMITATION SHALL APPLY WHETHER OR NOT SUCH DAMAGES ARE FORESEEABLE, OR WHETHER VELOSTING HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
                    <p className='mb-[30px]'><b>Allocation of Risk:</b> You (the Client) and Velosting understand and agree that, to the extent permitted by applicable law, the foregoing exclusions and limitations of liability represent the parties' agreement as to allocation of risk between them in connection with their respective obligations under this Agreement. The fees payable to Velosting reflect, and are set in reliance upon, this allocation of risk and the exclusions and limitations of liability set forth in this Agreement.</p>
                    <h3>INDEMNIFICATION</h3>
                    <p className='mb-[30px]'>You agree to indemnify and hold Velosting and its affiliates, directors, officers, employees, and agents harmless from and against any liabilities, losses, damages or costs, including reasonable attorneys' fees, incurred in connection with or arising from any third-party allegations, claims, actions, disputes, or demands asserted against any of them as a result of or relating to Your Content, your use of the Services or any wilful misconduct on your part.</p>
                    <h3>AGREEMENT</h3>
                    <p className='mb-[15px]'><b>Entire Agreement:</b> These TOS and all documents incorporated herein by reference constitute the complete agreement between the parties with respect to the subject matter hereof and supersedes and replaces all prior or contemporaneous discussions, negotiations, understandings and agreements, written or oral, regarding such subject matter.</p>
                    <p className='mb-[15px]'><b>Severability:</b> Should any provision of this Agreement be held to be invalid or unenforceable by a court of competent jurisdiction, that provision will be enforced to the extent permissible, and all other provisions will remain in effect and are enforceable by the parties.</p>
                    <p className='mb-[15px]'><b>Waiver:</b> No waiver of any part of this Agreement will be deemed to be a waiver of any other provision. No term of this Agreement will be deemed to be waived by reason of any previous failure to enforce it. No term of this Agreement may be waived except in a writing signed by the party waiving enforcement.</p>
                    <p className='mb-[30px]'><b>Interpretation:</b> The headings used in the Terms are for convenience of reference only. No provision of the Terms will be interpreted against any party merely because that party or its legal representative drafted the provision. All remedies are cumulative. Throughout the TOS, the term "including" or the phrases "e.g.," or "for example" have been used to mean "including, without limitation".</p>
                    <h3>ASSIGNMENT</h3>
                    <p className='mb-[15px]'><b>TOS:</b> You may not assign the agreement represented by these TOS, either in whole or in part, without the prior written consent of Velosting. Any other attempted transfer or assignment of rights hereunder shall be null and void.</p>
                    <p className='mb-[15px]'><b>Domain Names:</b> These TOS do not restrict your ability to transfer any domain for which you are the registrant. If Velosting is the registrar for the domain name, please request our "domain name transfer instructions" by sending an email to <Link to="https://help@Velosting.com">help@Velosting.com.</Link>. We will send you the specific details and information about transfer of ownership.</p>
                    <p className='mb-[30px]'><b>Velosting:</b> Velosting may assign its rights and obligations hereunder without your prior consent.</p>
                    <h3>NOTICE</h3>
                    <p className='mb-[30px]'><b>Notice:</b> Any notice or other significant communication given to you pursuant to the Terms will be in writing, addressed to any email address or address that you provided to Velosting when acquiring your first Service (as updated by you in accordance with section 3.2) and sent to you by email or by nationally recognized overnight courier as applicable. Any notice or other significant communication given to Velosting pursuant to the TOS will be in writing and sent to Velosting at the address then listed on the Site in the Contact Us section by fax or nationally recognized courier. Notices will be deemed to have been received one business days following: (i) email transmission by Velosting to you; (ii) deposit with a globally recognized overnight delivery service, all delivery charges pre-paid; or (iii) transmission if sent by facsimile and receipt confirmed by the facsimile machine used.</p>
                    <h3>OTHER</h3>
                    <p className='mb-[15px]'><b>Governing Law:</b> This Agreement will be governed by the laws of the Republic of India applicable therein, without reference to the conflict of laws provisions. The parties consent to the jurisdiction of the courts of Chandigarh, India.</p>
                    <p className='mb-[15px]'><b>Independent Contractors:</b> The relationship between the parties is that of independent contractors, and not that of partnership, joint venture, employment, franchise or agency. Neither party may incur any obligations on the other's behalf without the other's prior written consent, except as otherwise expressly provided herein.</p>
                    <p className='mb-[30px]'><b>Force Majeure:</b> Neither party will be liable for any failure or delay in its performance under this Agreement due to any cause beyond its reasonable control that could not have been avoided by the exercise of reasonable foresight provided that such party gives the other party prompt notice of such cause and uses reasonable commercial efforts to correct such failure or delay in performance.</p>
                    <h3>AMENDMENT</h3>
                    <p className='mb-[15px]'>Velosting may change the TOS from time to time and at any time. When Velosting changes the TOS, Velosting will: (i) post the updated version of the TOS on the Site together with the date on which it was revised; and (ii) on home page for the Site for at least 30 days following any change to the TOS post a notice that the TOS have been updated.</p>
                    <p className='mb-[15px]'>As well, Velosting may, but is not obliged to, ask you to actively confirm your consent to the revised TOS. If Velosting does not do so, but you continue to use the Services or Site after the changes come into effect, you will be deemed to have agreed to abide by the revised TOS. If you do not agree with the revised TOS without qualification, terminate any existing Services that you are receiving from Velosting and instruct Velosting to disable any password for the Site assigned to you</p>
                    <p className='mb-[15px]'>Velosting reserves the right, in its sole discretion, to change or modify the Site from time to time including but not limited adding or removing functionality or features or changing its name.</p>
                </div>
            </section>
        </Layout>
    )
}

export default TermsConditions
